### ISSUE TITLE
CI failing on Julia < 1.4 because `only` requires Julia 1.4

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaSIMD/HostCPUFeatures.jl#1]

**Comment by chriselrod** [comment]
Thanks -- I should've fixed it in this commit:
https://github.com/JuliaSIMD/HostCPUFeatures.jl/commit/6a0c9a0355abb2d4f8ba2033f8c52fe2c042f277
Did I miss something?

**Comment by DilumAluthge** [comment]
Whoops you're right. I was looking at an old CI run.
