### ISSUE TITLE
Comparison with CpuId.jl and Hwloc.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaSIMD/HostCPUFeatures.jl#14]
Can you please elaborate on the main differences to these other existing efforts?

**Comment by chriselrod** [comment]
This library gives information on features, such as FMA or AVX512BW, and defines compile time constants that can be used for code generation.

**Comment by juliohm** [comment]
I understand that these efforts can't be merged into a single project with multiple maintainers. Thanks for clarifying the differences.
